name: WEB_CI
'on':
  - push
jobs:
  types-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run types-checking
  unit-tests:
    needs: types-checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run test
  deploy:
    needs: unit-tests
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Creating .env file
        run: |
          touch .env
          echo SUPABASE_URL=${{ secrets.SUPABASE_URL }} >> .env
          echo SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} >> .env
      - name: Building the dist folder
        run: |
          npm ci
          npm run build --if-present
      - name: That's what I built
        run: ls dist/*
      - name: Uploading static contents to web server
        env:
          ID_RSA: '${{secrets.ID_RSA}}'
          USER: '${{secrets.VPS_USER}}'
          HOST: '${{secrets.VPS_IP}}'
          SERVER_PATH: '${{secrets.STAGING_PATH}}'
        run: |
          ssh_path="$HOME/.ssh"
          mkdir "$ssh_path"
          echo "$ID_RSA" >> "$ssh_path/id_rsa"
          chmod 400 "$ssh_path/id_rsa"
          ssh-keyscan -t rsa "$HOST" >> "$ssh_path/known_hosts"
          rsync -a --delete ./dist/ "$USER@$HOST:$SERVER_PATH"
