# This is a basic workflow to help you get started with Actions

name: STAGING_DEPLOY

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_run:
    workflows: [BASE_CHECKS]
    types: [completed]
    branches: [develop]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 'Creating .env file'
        run: |
          touch .env
          echo SUPABASE_URL=${{ secrets.SUPABASE_URL }} >> .env
          echo SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} >> .env

      - name: Building the dist folder
        run: |
          npm ci
          npm run build --if-present
      - name: That's what I built
        run: ls dist/*

      - name: Uploading static contents to web server
        env:
          ID_RSA: ${{secrets.ID_RSA}}
          USER: ${{secrets.VPS_USER}}
          HOST: ${{secrets.VPS_IP}}
          SERVER_PATH: ${{secrets.STAGING_PATH}}
        run: |
          ssh_path="$HOME/.ssh"
          mkdir "$ssh_path"
          echo "$ID_RSA" >> "$ssh_path/id_rsa"
          chmod 400 "$ssh_path/id_rsa"
          ssh-keyscan -t rsa "$HOST" >> "$ssh_path/known_hosts"
          rsync -a --delete ./dist/ "$USER@$HOST:$SERVER_PATH"